version: '3'

services:
  tor:
    container_name: tor
    build:
      context: ./build/package/tor
    restart: always
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "curl -sS --socks5-hostname localhost:9050 https://check.torproject.org/api/ip | grep '\"IsTor\": *true'"]
      interval: 10s
      timeout: 5s
      retries: 5

  pryingdeep:
    container_name: pryingdeep
    build:
      context: .
      dockerfile: ./Dockerfile

    command:
      - '/bin/sh'
      - '-c'
      - './pryingdeep crawl'

    network_mode: host
    depends_on:
      tor:
        condition: service_healthy