version: '3'

services:
  tor:
    container_name: tor
    build:
      context: ./build/package/tor
    restart: always

   
    network_mode: host


  api:
    container_name: pryingdeep
    build:
      context: .
      dockerfile: ./Dockerfile


    # Adjust the sleep value depending on how fast your computer starts tor. B
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 8 && ./pryingdeep'

    network_mode: host