version: '3'

services:
  tor:
    container_name: tor
    build:
      context: ./build/package/tor
    restart: always

    ports:
      - "9050:9050"
    healthcheck:
      test: ["CMD", "curl", "-socks5", "localhost:9050", "-k", "https://check.torproject.org/api/ip"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    container_name: pryingdeep
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      tor:
        condition: service_healthy


